// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.23.4
// source: proto/board.proto

package board

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,3,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBoardRequest) Reset() {
	*x = CreateBoardRequest{}
	mi := &file_proto_board_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBoardRequest) ProtoMessage() {}

func (x *CreateBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBoardRequest.ProtoReflect.Descriptor instead.
func (*CreateBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_proto_rawDescGZIP(), []int{0}
}

func (x *CreateBoardRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateBoardRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateBoardRequest) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

type GetBoardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBoardRequest) Reset() {
	*x = GetBoardRequest{}
	mi := &file_proto_board_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBoardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBoardRequest) ProtoMessage() {}

func (x *GetBoardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBoardRequest.ProtoReflect.Descriptor instead.
func (*GetBoardRequest) Descriptor() ([]byte, []int) {
	return file_proto_board_proto_rawDescGZIP(), []int{1}
}

func (x *GetBoardRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type BoardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OwnerId       string                 `protobuf:"bytes,4,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoardResponse) Reset() {
	*x = BoardResponse{}
	mi := &file_proto_board_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoardResponse) ProtoMessage() {}

func (x *BoardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_board_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoardResponse.ProtoReflect.Descriptor instead.
func (*BoardResponse) Descriptor() ([]byte, []int) {
	return file_proto_board_proto_rawDescGZIP(), []int{2}
}

func (x *BoardResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BoardResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *BoardResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BoardResponse) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

var File_proto_board_proto protoreflect.FileDescriptor

const file_proto_board_proto_rawDesc = "" +
	"\n" +
	"\x11proto/board.proto\x12\x05board\"g\n" +
	"\x12CreateBoardRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x03 \x01(\tR\aownerId\"!\n" +
	"\x0fGetBoardRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"r\n" +
	"\rBoardResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\bowner_id\x18\x04 \x01(\tR\aownerId2\x88\x01\n" +
	"\fBoardService\x12>\n" +
	"\vCreateBoard\x12\x19.board.CreateBoardRequest\x1a\x14.board.BoardResponse\x128\n" +
	"\bGetBoard\x12\x16.board.GetBoardRequest\x1a\x14.board.BoardResponseB\rZ\vproto/boardb\x06proto3"

var (
	file_proto_board_proto_rawDescOnce sync.Once
	file_proto_board_proto_rawDescData []byte
)

func file_proto_board_proto_rawDescGZIP() []byte {
	file_proto_board_proto_rawDescOnce.Do(func() {
		file_proto_board_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_board_proto_rawDesc), len(file_proto_board_proto_rawDesc)))
	})
	return file_proto_board_proto_rawDescData
}

var file_proto_board_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_board_proto_goTypes = []any{
	(*CreateBoardRequest)(nil), // 0: board.CreateBoardRequest
	(*GetBoardRequest)(nil),    // 1: board.GetBoardRequest
	(*BoardResponse)(nil),      // 2: board.BoardResponse
}
var file_proto_board_proto_depIdxs = []int32{
	0, // 0: board.BoardService.CreateBoard:input_type -> board.CreateBoardRequest
	1, // 1: board.BoardService.GetBoard:input_type -> board.GetBoardRequest
	2, // 2: board.BoardService.CreateBoard:output_type -> board.BoardResponse
	2, // 3: board.BoardService.GetBoard:output_type -> board.BoardResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_board_proto_init() }
func file_proto_board_proto_init() {
	if File_proto_board_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_board_proto_rawDesc), len(file_proto_board_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_board_proto_goTypes,
		DependencyIndexes: file_proto_board_proto_depIdxs,
		MessageInfos:      file_proto_board_proto_msgTypes,
	}.Build()
	File_proto_board_proto = out.File
	file_proto_board_proto_goTypes = nil
	file_proto_board_proto_depIdxs = nil
}
